### ISSUE TITLE
Could I move my 'textbooks-with-jupyter' repo here at some point?

### ISSUE THREAD

**Issue by choldgraf** [jupyter4edu/ideas#8]
👋 hello - me and @samlau95 have been working on a template repo to let people create "textbooks" with Jupyter Notebooks served as Jekyll pages: https://github.com/choldgraf/textbooks-with-jupyter

it's currently hosted under my name, but I've been hoping to find a home for the repo that makes it look less like it is "my" project and hopefully start building a community around it. Do you think this is in-scope with the jupyter-education organization? I am happy to transfer it over, but no worries if you've got other plans for this org!

**Comment by lheagy** [comment]
Thanks @choldgraf! I think that this org has potential to be a good home for the Jupyter book project. With respect to scope, my take is that we would like to keep most of the conversations (and repos) directed to pedagogy and promoting ideas around using Jupyter in education with less emphasis on tech. That said, tech-projects that are targeted directly at enabling the use of Jupyter for education I think do have a place here. @willingc and I talked a bit about scope at JupyterCon a while ago. 

I would be very curious to get opinions from the other @jupyter4edu/authors on scope.

**Comment by zingale** [comment]
I think it would be nice to have enabling technologies be part of the same org, so I'm +1

**Comment by moorepants** [comment]
Sounds good to me!

**Comment by labarba** [comment]
I support the idea of `jupyter4edu` org growing to host projects aimed at helping educators in various ways, and the Jupyter Book project fits the bill. (BTW, I get a bit confused by the singular vs. plural use of "Book" in repo and title…)

**Comment by choldgraf** [comment]
Hey all - sounds good! I'll leave this issue open a few more days in case anybody else has differing opinions. Will transfer over the repo later this week if there aren't any -1s.

@labarba good point on the plural vs. singular, I changed the title back to singular!

**Comment by labarba** [comment]
@choldgraf A couple of plurals remain in sections of the Readme.

**Comment by willingc** [comment]
Hmm... While I'm okay with moving this particular project moving to this org, I'm a bit hesitant to move tools into the org. We have many orgs with Jupyter technical projects where a wide variety are used for teaching. When we had talked about a jupyter in education org over in the Jupyter Steering Council, we were looking for a home for best practices and content to improve Jupyter's use in education. Moving tools into the org implies that the org maintainers will maintain the tool. Personally, I would prefer creating another org if we will be moving more than 1 or 2 tools here.

**Comment by labarba** [comment]
@willingc Good point about who is maintainer. I agree we proceed with care. For `jupyter-book`, would it work with a team in the org that is specifically designated as maintainers of the tool?

**Comment by willingc** [comment]
I'm okay with that for now. Yet, I really want the content and best practices to be the featured things in this org. Tools change faster than books, and the tools will push the book and educational content lower in the GitHub display of projects (since GitHub sorts most recent to least recent changes).

**Comment by willingc** [comment]
Overall, I would far prefer to have an awesome list for Jupyter in Edu that refers out to the technical projects.

**Comment by labarba** [comment]
Going back to the "tools" versus "edu practices" discussion, @choldgraf: why don't you transfer the project to the main Jupyter org? It does seem more appropriate.

**Comment by jedbrown** [comment]
Seems to me that nbgrader is every bit as education-specific as jupyter-book and is hosted in the main Jupyter organization, thus demonstrating that they are receptive to it. I think that would be the most prominent place to host jupyter-book, so I would recommend trying that first.

**Comment by lheagy** [comment]
:wave: Hi @choldgraf, it looks like you moved it to the jupyter org, is that a home you are happy with? if so, can we close this issue? Thanks!

**Comment by choldgraf** [comment]
yep! https://github.com/jupyter/jupyter-book
